INSERT INTO categoria (id_categoria, nombre) VALUES 
(1, 'Desayuno'),
(2, 'Almuerzo'),
(3, 'Cena'),
(4, 'Brunch'),
(5, 'Merienda'),
(6, 'Aperitivo / Snack'),
(7, 'Entrada'),
(8, 'Plato Principal'),
(9, 'Postre'),
(10, 'Guarnición'),
(11, 'Sopa / Caldo'),
(12, 'Ensalada'),
(13, 'Bebida Caliente'),
(14, 'Cóctel'),
(15, 'Batido / Smoothie'),
(16, 'Panadería y Repostería'),
(17, 'Vegetariano'),
(18, 'Vegano'),
(19, 'Sin Gluten'),
(20, 'Sin Lácteos'),
(21, 'Keto (Cetogénica)'),
(22, 'Paleo'),
(23, 'Baja en Calorías (Light)'),
(24, 'Alta en Proteínas'),
(25, 'Sin Azúcar'),
(26, 'Baja en Carbohidratos'),
(27, 'Mexicana'),
(28, 'Italiana'),
(29, 'Japonesa'),
(30, 'China'),
(31, 'India'),
(32, 'Mediterránea'),
(33, 'Tailandesa'),
(34, 'Peruana'),
(35, 'Española'),
(36, 'Francesa'),
(37, 'Al Horno'),
(38, 'A la Parrilla / Asado'),
(39, 'Frito'),
(40, 'Al Vapor'),
(41, 'Rápido y Fácil (Menos de 30 min)'),
(42, 'Económico'),
(43, 'Para Niños');